-- MariaDB dump 10.19  Distrib 10.6.7-MariaDB, for debian-linux-gnu (x86_64)
--
-- Host: localhost    Database: SIO1-projet1
-- ------------------------------------------------------
-- Server version	10.6.7-MariaDB-2ubuntu1.1

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Current Database: `SIO1-projet1`
--

CREATE DATABASE /*!32312 IF NOT EXISTS*/ `SIO1-projet1` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;

USE `SIO1-projet1`;

--
-- Table structure for table `quizz`
--

DROP TABLE IF EXISTS `quizz`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `quizz` (
  `qcm_id` bigint(20) AUTO_INCREMENT,
  `qcm_question` varchar(512) DEFAULT NULL,
  `qcm_r1_resultat` tinyint(1) DEFAULT NULL,
  `qcm_r1_proposition` varchar(256) DEFAULT NULL,
  `qcm_r2_resultat` tinyint(1) DEFAULT NULL,
  `qcm_r2_proposition` varchar(256) DEFAULT NULL,
  `qcm_r3_resultat` tinyint(1) DEFAULT NULL,
  `qcm_r3_proposition` varchar(256) DEFAULT NULL,
  `qcm_r4_resultat` tinyint(1) DEFAULT NULL,
  `qcm_r4_proposition` varchar(1024) DEFAULT NULL,
  UNIQUE KEY `quizz_qcm_id_IDX` (`qcm_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=130 DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `quizz`
--

LOCK TABLES `quizz` WRITE;
/*!40000 ALTER TABLE `quizz` DISABLE KEYS */;
INSERT INTO `quizz` VALUES 
(1,'Q1. Comment pouvez-vous vérifiez la version de git installé?',0,'git --v',1,'git --version',0,'git --option',0,'git --current'),
(2,'Q2. Quelle commande permet de créer une connexion entre un déôt local et un dépôt distant ?',0,'git remote add new',1,'git remote add origin',0,'git remote new origin',0,'git remote origin\n\n[Reference](https://stackoverflow.com/questions/20291731/how-to-connect-to-a-remote-git-repository)'),
(3,'Q3. Décrivez ce que font ces commandes sur l\'historique de vos commits:\n\n```bash\ngit reset --hard HEAD~5\ngit merge --squash HEAD@{1}\n```\n',0,'They reset the HEAD to the fifth commit in the repo, then merge to the master branch.',1,'The current branch\'s HEAD is reset back five commits, then prior commits are squashed into a single commit.',0,'They delete the last five commits.',0,'They merge the last five commits into a new branch.\n\n**Explanation:**\n\n- `git reset --hard HEAD~5` resets the current branch to the commit just before the last 5 (see `man gitrevisions` for details about this notation and other cool alternatives like `HEAD@{2 days ago}`). As it is a hard reset, it will also overwrite every change in the working tree as well. See `man git-reset`.\n- `git merge --squash HEAD@{1}` HEAD@{1} is where the branch was just before the previous command (again, see `man gitrevisions`). This command sets the state of the index to be as it would just after a merge from that commit. This whole operation could be a way to take 5 commits from a branch in which you started a new feature and squash them to a single commit, a meaningful one.'),
(4,'Q4. Your current project has several branches; master, beta, and push-notifications. You\'ve just finished the notification feature in the push-notification branch, and you want to commit it to beta branch. How can you accomplish this?',0,'Checkout the push-notifications branch and run git merge beta',0,'Checkout the master branch and run git merge beta -> push-notification',0,'Delete the push-notification branch and it will be committed to the master branch automatically',1,'Checkout the beta branch and run git merge push-notification'),
(5,'Q5. Which of the following is 1 you when you use the following command?\n\n`git add -A`\n',1,'All new and updated files are staged',0,'Files are staged in alphabetical order.',0,'All new files are staged',0,'Only updated files are staged'),
(6,'Q6. What will the following command print to the Terminal?\n\n`git remote -v`\n',1,'A list of remote repositories and their URLs',0,'The current git version you\'re running',0,'An inline editor for modifying remote repositories',0,'The last 5 git versions you\'ve installed'),
(7,'Q8. What does the following command do to the git repository?\n\n`git reset --soft HEAD^`\n',0,'It deletes all previous commits and reset the repository history back to its initial state.',0,'It resets the working branch to the first commit.',0,'It keeps the HEAD at the current commit, but clears all previous commits.',1,'It sets HEAD to the previous commit and leaves changes from the undone commit in the stage/index.'),
(8,'Q9. You find a bug in your project, but can\'t locate where it was introduced in the commit history. How would you diagnose this problem?',0,'Manually backtrack through your commit history.',0,'Use git search -diff to compare all commits in your repository history.',0,'Run a git rebase to find the buggy commit.',1,'Use git bisect to compare the buggy commit to an early commit that works as expected.'),
(9,'Q10. Why would the following command be used?\n\n`git rebase -i HEAD~10`\n',0,'To run a comparative search of the last 10 commits for differences',1,'To list the last 10 commits and modify them with either the squash or fixup command',0,'To delete the last 10 commits and reset the HEAD',0,'In order to locally cache the last 10 commits'),
(10,'Q11. Why would you use a pre-receive hook in your remote repository?',0,'You wouldn\'t, you would use it in the local repository',1,'To execute a script when a remote receives a push that is triggered before any refs are updated',0,'To fire a script after updates are made to the remote repository',0,'To debug all commit tags and release versions'),
(11,'Q12. What option can you use to apply git configurations across your entire git environment?',0,'`--all`',0,'`--master`',1,'`--global`',0,'`--update`'),
(12,'Q13. How could you squash multiple commits together without using git merge --squash?',0,'Caching',0,'You can\'t. git merge --squash is the only git command for that operation.',1,'Rebasing',0,'Reflogging'),
(13,'Q14. If you cloned an existing git repository, what would happen?',0,'A new copy would overwrite the central repository',1,'A copy of the repository would be created on your local machine',0,'Nothing, cloning is not a supported git function',0,'A copy of the repository would be created on the hosting platform'),
(14,'Q15. How can you display a list of files added or modified in a specific commit?',0,'Find the commit in the remote repository, as that\'s the only place that kind of information is stored.',1,'Use the `diff-tree` command with the commit hash.',0,'Run `git commit --info` with the commit hash.',0,'Access the commit stash data with `git stash`.'),
(15,'Q16. What files is this .gitignore programmed to leave out?\n\n```shell\n#.swift\nbuild/\n\n*.txt\n*.metadata\n```\n',0,'All files with a .swift, .txt, or metadata file extension, as well as the entire build directory',0,'Only the build directory',1,'All files in the build directory, as well as files ending with .txt or .metadata',0,'Only files with .swift and .txt extensions.\n\nA line starting with `#` serves as a comment. Hence `# .swift` does not do anything. See `man gitignore`.'),
(16,'Q17. After you make changes to a local repository, you run the following command. What will this do?\n\n`git commit -a -m \"Refactor code base\"`\n',0,'Nothing, you can\'t use multiple options in the same command',0,'Adds all new files to the staging area',0,'Commits all new files with a message',1,'Adds all modified files to the staging area, then commits them with a message'),
(17,'Q18. After checking your git status you get the following output, which shows the file beta-notes.js in the commit but also unstaged. How can this situation occur?\n\n```shell\nChange to be committed:\n\n(use \'git reset HEAD <file>...\' to unstage)\nmodified: beta-notes.js\nChanges not staged for commit:\n(use \'git add <file>...\' to update what will be committed)\n(use \'git checkout --<file>...\' to discard changes in working directory)\n\nmodified: beta-notes.js\n```\n',0,'There were two copies of beta-notes.js but one was deleted',1,'beta-notes.js was staged, then modified afterwards, creating two different versions of the file',0,'Two copies of beta-notes.js were created, but only one is being tracked',0,'There are two tracked copies of beta-notes.js, but one was removed from the commit'),
(18,'Q19. Where are files stored before they are committed to the local repository?',0,'Saved files',0,'git documents',1,'Staging area',0,'git cache'),
(19,'Q20. What commands would you use to force an overwrite of your local files with the master branch?',0,'⠀\n  ```bash\n  git pull --all\n  git reset --hard origin/master\n  ```',0,'⠀\n  ```bash\n  git pull -u origin master\n  git reset --hard master\n  ```',0,'⠀\n  ```bash\n  git pull origin master\n  git reset --hard origin/myCurrentBranch\n  ```',1,'⠀\n\n  ```bash\n  git fetch --all\n  git reset --hard origin/master\n  ```\n\n- The command `pull` is `fetch` followed by either `merge` or `rebase` (in this case, `merge`). We don\'t want to merge. Merge would be an action to our **repository**. We just want to overwrite our **local files**.'),
(20,'Q21. Which statement is 1 when you use the git add -A command?',0,'Only new files in the working directory are staged to the index.',1,'All new and updated files from the working directory are staged to the index.',0,'All files in the working directory are staged to the index in alphabetical order.',0,'Only updated files in the working directory are staged to the index.'),
(21,'Q22. You find that your project has a tag and branch both named push-notifications, which causes confusion when trying to print out given reference. How can you specify which branch you want to look at?',0,'use git show refs/push-notifications',0,'use git show push-notifications',0,'use git show heads/refs/push-notifications',1,'use git show refs/heads/push-notifications\n\n[Reference](https://geedew.com/fixing-git-branch-and-tag-name-collision/)'),
(22,'Q23. Your team lead needs a list of all commits that will be moved before you perform a rebase. Which command can you use to access that information?',0,'git rebase -log',1,'git rebase -i',0,'git rebase -verbose',0,'git rebase -all'),
(23,'Q24. What is the operation doing given the Git commands below?\n\n```\ngit bisect start\ngit bisect bad 5d41402abc4b2a76b9719d911017c592\ngit bisect good 69faab6268350295550de7d587bc323d\n```\n',0,'It runs a merge of a good commit that is discovered using a known bad commit and known good commit',0,'It marks a commit for deletion using a known bad commit and known good commit to determine which commit introduced a bug',0,'It defines a bad commit and resets the HEAD using a known bad commit and known good commit',1,'It performs a binary search using a known bad commit and known good commit to determine which commit introduced a bug'),
(24,'Q25. In a situation where you have several commits for a single task, what is the most efficient way to restructure your commit history?',0,'Cherry pick the related commits to another branch.',0,'Delete the task commits and recommit with a new message.',1,'Squash the related commits together into a single coherent commit.',0,'Stash the related commits under a new hash.'),
(25,'Q26. Which of the following is 1 of the git push command?',1,'By default a push doesn\'t send tags to the remote repository.',0,'Commits can only be tagged when they are created.',0,'Tags are pushed to the remote repository with their respective commits.',0,'Only annotated tags are automatically pushed to the remote repository with a commit.\n\n[Reference](https://git-scm.com/book/en/v2/Git-Basics-Tagging#_sharing_tags)'),
(26,'Q27. After pushing commits to the remote repository for the first time using the command below, what shorthand command can you use in future?\n\n```bash\ngit push -u origin master\n```\n',0,'git push master',0,'git push origin',0,'Same as before, git push -u origin master',1,'git push'),
(27,'Q28. How would you create a custom shortcut or command across your git environment?',0,'Run git hotfix with the shortcut name.',0,'Assign a shortcut or command using git options file.',0,'Use the git custom-key command.',1,'Create an alias using the git config command.'),
(28,'Q29. What is the status of the beta-notes.js file in the following output?\n\n```shell\nChanges not staged for commit:\n(use \'git add <file>...\' to update what will be committed)\n(use \'git checkout -- <file>...\' to discard changes in working directory)\n\nmodified: beta-notes.js\n```\n',0,'beta-notes.js is untracked and has been modified.',1,'beta-notes.js is a tracked file and has been modified, but has not been added to the current commit.',0,'beta-notes.js is untracked but has been added to the current commit.',0,'beta-notes.js is tracked, and the modified file has been added to the current commit.'),
(29,'Q30. What command would let you modify your previous commit?',0,'--fix',0,'--quickfix',0,'--modify',1,'--amend'),
(30,'Q31. What is the best way to characterize the git commit structure?',0,'Data array',1,'Data log',0,'Data snapshot',0,'Data dictionary'),
(31,'Q32. What change will the following command make to the staging area files?\n\n`git rm --cached testfile.js`\n',1,'testfile.js will be removed from the staging area and its changes no longer tracked.',0,'testfile.js will be removed from the staging area but its changes will still be tracked.',0,'A copy of testfile.js will be cached on your desktop.',0,'The current copy of testfile.js will be saved in the staging area.'),
(32,'Q33. After you\'ve successfully merged two branches and committed the changes, what is the next step in keeping your git structure organized?',0,'Use the git reset --soft HEAD to roll back one commit.',1,'Run git branch -d `<branch name>` to delete the merged branch.',0,'Use git clear-all to clean up any hanging files.',0,'Run git rebase to move the current commit to its original location.'),
(33,'Q34. While modifying a file, you\'re unexpectedly assigned an urgent bug fix on another branch. How can you temporarily save your local work without committing?',0,'This is not possible, as you cannot save locally without committing.',0,'Run git hold to save a local copy of what you\'re doing to return to later.',0,'Save your work with git local-cache.',1,'Use git stash to save your work and come back later and reapply the stashed commit.'),
(34,'Q35. What command would you use to create a new git repository?',0,'git add',0,'git start',0,'git new',1,'git init'),
(35,'Q36. While working on a feature branch you try to use \'git rerere\' to solve a recurring merge conflict but nothing is happening. What could be causing this issue?',0,'The \'-all\' option isn\'t added to the command.',1,'\'rerere.enabled\' isn\'t enable in the config file.',0,'The commit hash is missing.',0,'The filepath isn\'t specified.'),
(36,'Q37. Which setting determines what pager is used when Git pages output?',0,'core.page',0,'page',0,'pager',1,'core.pager'),
(37,'Q38. What does commit object contain?',0,'A set of files, representing the state of a project at a given point of time.',0,'Reference to parent commit objects.',1,'An SHA1 name, a 40-character string that uniquely identifies the commit object.',NULL,''),
(38,'Q39. Which option enables inclusion of committer name in custom log format?',0,'%ce',0,'%cr',0,'%cd',1,'%cn'),
(39,'Q40. How many ways are present in Git to integrate changes from one branch into another?',0,'3',0,'5',1,'2',0,'4\n\n[Reference link](https://git-scm.com/book/en/v2/Git-Branching-Rebasing)\n`In Git, there are two main ways to integrate changes from one branch into another: the merge and the rebase.`'),
(40,'Q41. Which user should be created first during setting up of SSH?',1,'git',0,'admin',0,'root',0,'None of these'),
(41,'Q42. Which command will list tags with the 1.4.2 series?',0,'git tag \'v1.4.2\'',1,'git tag -I \'v1.4.2.*\'',0,'git tag-list \'v1.4.2*\'',0,'git tag \'v1.4.2*\''),
(42,'Q43. Which of the following is an integration manager?',0,'lieutenants',1,'benevolent dictator',0,'Depends upon project type',0,'Depends upon data'),
(43,'Q44. Which Git command begins tracking of a new file?',1,'add',0,'addfile',0,'begin',0,'track'),
(44,'Q45. Which of the following is called dumb protocol?',0,'All of these',0,'SSH',0,'Git',1,'HTTP'),
(45,'Q46. Which key press returns a set of suggestions to pick from, when writing a Git command?',0,'Control',0,'Shift',1,'Tab',0,'Alt'),
(46,'Q47. Which of these terms best describes Git?',1,'Distributed Version Control System',0,'Issue Tracking System',0,'Integrated Development Environment',0,'Web-Based Repository Hosting Service'),
(47,'Q48. Which command gets a copy of an existing Git repository?',0,'duplicate',0,'replicate',0,'copy',1,'clone'),
(48,'Q49. How does Git think of its data?',0,'File',0,'None of these',1,'Snapshot',0,'Folder'),
(49,'Q50. Which option enables inclusion of author name in custom log format?',0,'%am',0,'%ad',0,'%ae',1,'%an'),
(50,'Q51. Which version onwards did Git offer reversing a file back to what it looked like when last committed?',0,'1.7',1,'1.6',0,'2.0',0,'1.8'),
(51,'Q52. Which strategy is used by Git for merging two branches?',0,'LIFO',1,'recursive',0,'FIFO',0,'octopus'),
(52,'Q53. What does refs store?',1,'SHA-1 value',0,'None of these',0,'Branch name',0,'Project name'),
(53,'Q54. What Language is used in GIT?',1,'C',0,'C++',0,'C#',0,'Java'),
(54,'Q55. What is usually the extension of file which has the public key?',0,'ssh',1,'pub',0,'key',0,'pk'),
(55,'Q56. What is the difference between initializing a normal repo and a bare repo?',0,'Bare repos store their git history in a .git subfolder.',0,'Bare repos do not have the .git extension.',1,'Bare repos do not come with working or checked-out source files.',0,'Bare repos should be used for local rather than remote repos.'),
(56,'Q57. How many individual commits can a single repository have?',1,'any number of commits',0,'only one commit local per repository',0,'only three commits per branch',0,'only one commit per HEAD'),
(57,'Q58. What types of tags does Git support?',0,'heavy and concise',0,'lightweight and immutable',0,'heavy and annotated',1,'lightweight and annotated'),
(58,'Q59. After staging a series of changes to the index, which command could you use to review them prior to a commit?',1,'git diff --cached',0,'git diff',0,'git diff --HEAD',0,'git status -v -v'),
(59,'Q60. What does the git stash drop command do?',1,'removes the most recent stash entry',0,'deletes the stash',0,'lists everything in the stash',0,'throws away the oldest entry'),
(60,'Q61. What command creates a new branch from the currently checked-out branch?',0,'`git -b checkout <nameOfBranch>`',0,'`git branch`',0,'`git checkout <nameOfBranch>`',1,'`git checkout -b <nameOfBranch>`'),
(61,'Q62. After mistakenly staging a file named myFile to the index, how would you remove it from the index to exclude it from your next commit?',0,'Use git reset HEAD^.',1,'Use git reset myFile.txt.',0,'Use git -rm myFile.txt.',0,'Use git reset.'),
(62,'Q63. What happens if you run this command from your master branch?\n\n```bash\ngit checkout -b beta-test\n```\n',0,'The beta-test branch will be checked out of the current commit.',0,'The beta-test branch will be checked out and deleted.',1,'A new branch called beta-test will be created and switched to.',0,'The beta-test branch will be merged with the master branch.'),
(63,'Q64. How does Git internally manage branches?',1,'by creating a pointer to the most recent snapshot/commit for the branch.',0,'by creating a data array of branches in the same repository.',0,'by creating a data dictionary of code changes.',0,'be creating a debug log that stores repository changes.'),
(64,'Q65. You want to perform a git reset but cannot recall all of the available options. What command would you use to see a description of them?',1,'git help reset',0,'git -h reset',0,'git options reset',0,'git reset help'),
(65,'Q66. What is a remote repository?',0,'a version of the repository that mirrors changes made in the local repository\'s master branch for open-source collaboration efforts',0,'the lead repository elected by the Git arbitrator found within local repositories of collaborating team members',0,'a read-only version of the repository stored on a backup server in case local repositories become lost or corrupted',1,'a version of the repository hosted on the internet or network that is pushed to or pulled from by collaborators'),
(66,'Q67. After modifying some existing files in a repository, you decide to discard the changes. What command can you use?',1,'git restore',0,'git undo',0,'git clean',0,'git checkout'),
(67,'Q68. After starting to merge a feature branch into your master branch, you encounter a merge conflict and decide you do not want to perform the merge. How can you stop the merge and restore to the pre-merge state?',0,'Use git restore -p.',0,'Use git merge -u.',1,'Use git merge --abort.',0,'Use git merge --undo.'),
(68,'Q69. If you have several commits for a single feature, what is the most efficient way to restructure your commit history?',0,'Use git stash to consolidate the commits under a new hash.',1,'Use git squash to consolidate the commits together into a single coherent commit.',0,'Delete the task commits and recommit with a new message.',0,'Use git cherry-pick to place the commits in another branch.'),
(69,'Q70. Which command correctly creates a lightweight tag?',1,'`git tag v3.8.1`',0,'`git tag --light \'v3.8.1\'`',0,'`git tag v3.8.1 --annotate -m \"<tagMessage>\"`',0,'`git tag -l v3.8.1`'),
(70,'Q71. What is the main issue with using git rebase when working with multiple developers?',0,'Rebase affects only your repository and creates a diff in the master branch.',0,'Rebase creates a temporary copy of the master branch in the remote repo.',0,'Rebase moves the HEAD of the remote master branch one commit forward.',1,'Rebase deletes all commit history for the new feature branch.'),
(71,'Q72. What Git workflow is used by teams that collaborate on a single branch and avoid creating long-lived development branches?',0,'Git flow',0,'Mainline flow',1,'Trunk-Based Development',0,'GitHub flow'),
(72,'Q73. Which option on the git log command allows you to limit output to commits made after certain date?',1,'`--since`',0,'`--sinceWhen`',0,'`-<n>`',0,'`--afterDate`'),
(73,'Q74. How would you delete unreachable objects older than a specified time from your project database?',0,'`git cache --obsolete <time>`',0,'`git branch --rebase <time>`',0,'`git delete --inert <time>`',1,'`git prune --expire <time>`'),
(74,'Q75. What conflicts can occur when forcing a push after rebasing?',1,'The remote master branch could have existing changes overwritten.',0,'The origin URL will be reset to its default value.',0,'The current HEAD will be deleted and can\'t be reinstated.',0,'Nothing, it\'s common practice to force a push after rebasing.'),
(75,'Q76. How does this command alter the currently checked-out branch?\n\n`git reset --soft HEAD^`\n',0,'It resets the working branch to the first commit.',1,'It sets HEAD to previous commit and leaves changes from the undone commit in the stage/index.',0,'It deletes all previous commits and resets the repository history back to its initial state.',0,'It keeps the HEAD at the current commit, but clears all previous commits.'),
(76,'Q77. What is the difference between Git and SVN?',0,'Git works only on Linux, while SVN works on all operating systems.',0,'SVN works only on Linux, while Git works on all operating systems.',1,'SVN is a centralized system, while Git is a distributed system.',0,'Git a centralized system, while SVN is a distributed system.'),
(77,'Q78. This command is an example of what kind of tag?\n\n`git tag -a v1.4 -m \'ABCD v1.5\'`\n',0,'verbose',1,'annotated',0,'lightweight',0,'deferred'),
(78,'Q79. What is the difference between a soft reset (`git reset --soft`) and a hard reset (`git reset –hard`) ?',1,'A soft reset only changes the commit that HEAD points to, while a hard reset resets the index and working tree to match the specified commit, discarding any changes.',0,'A soft reset caches the old HEAD pointer, while a hard reset deletes it entirely.',0,'A hard reset changes only where the HEAD is pointing, while a soft reset changes the HEAD and index.',0,'A hard reset caches the old HEAD pointer, while a soft reset deletes it entirely.'),
(79,'Q80. Consider the following Git workflow:\n\n![image](images/Git-WorkFlow.png)\nWhich of the following options is correct ?',0,'`1. Develop 2. Release 3. Hotfix 4. Feature 5. Master`',0,'`1. Master 2. Release 3. Hotfix 4. Feature 5. Develop`',0,'`1. Develop 2. Master 3. Hotfix 4. Feature 5. Develop`',1,'`1. Master 2. Hotfix 3. Develop 4. Feature 5. Release`'),
(80,'Q81. What information does the git config file store?',0,'shell scripts and flags',0,'keychain and account information',1,'local and global repository options',0,'pre-compile scripts and settings\n\n[Reference](https://www.atlassian.com/git/tutorials/setting-up-a-repository/git-config#:~:text=The%20git%20config%20command%20is,modify%20a%20configuration%20text%20file.)'),
(81,'Q82. What is version control?',0,'a type of architecture used to manage large databases',1,'a system that shows, tracks, and controls changes to a set of files over time',0,'a programmatic design pattern used to manage code between multiple engineering teams',0,'a type of software that links a project with a GitHub repository'),
(82,'Q83. What is the difference between using the git stash and git stash pop commands?',0,'git stash removes a commit from the repo history, while git stash pop saves changes to multiple branches.',0,'git stash saves changes to multiple branches, while git stash pop removes a commit from the repo history.',0,'git stash removes the most recent commit, while git stash pop saves current changes.',1,'git stash creates a stash entry, while git stash pop places the saved state onto the working directory.'),
(83,'Q84. Which command can be used to list the branches that have been merged into the currently checked-out branch?',0,'git master --status',0,'git branch --status',1,'git branch --merged',0,'git status --merged'),
(84,'Q85. How would you configure Git to abort a commit if a smoke test script fails?',0,'Create a post-commit shell script that triggers the action.',0,'Create a post-commit hook to trigger the script.',1,'Create a pre-commit hook to trigger the script.',0,'Create a pre-commit shell script that triggers the action.'),
(85,'Q86. Which use case is NOT a good candidate for a Git hook?',1,'state dependent environment changes',0,'continuous integration',0,'increasing code coverage',0,'enforcing commit rules'),
(86,'Q87. After starting to work on a new feature and creating new files in the working directory related to it, the customer determined the feature was no longer required. What command can be used to remove the untracked files from the working directory ?',1,'`git clean -f`',0,'`git rm .`',0,'`git reset HEAD`',0,'`git checkout .`'),
(87,'Q88. What information do Git reflogs (reference logs) store?',0,'shell script pointers and keychain credentials',1,'updates to branch tips and other references in the local repository',0,'release notes and hook script values',0,'tag and versioning information'),
(88,'Q89. You have just completed rebasing your master branch and need to manually update the remote master, even though there is a merge conflict. How can you accomplish this?',0,'`git push --overwrite`',0,'`git push --update`',0,'`git push --assert`',1,'`git push --force-with-lease`'),
(89,'Q90. What is the difference between `git fetch` and `git pull`\n',0,'`git fetch` creates a new branch off the master branch, while `git pull` creates a new branch off the local repository\'s master branch.',0,'`git pull` downloads new data from a remote repository without integrating it into local files, while `git fetch` updates the current HEAD branch with the latest changes from the remote server.',1,'`git fetch` updates remote tracking branches with changes from a remote repository, while `git pull` updates remote tracking branches with changes from a remote repository and merges them into their corresponding local branches.',0,'`git fetch` downloads and merges data from the local repository, while `git pull` informs your colleagues you are about to make changes to the master branch.'),
(90,'Q91. What command displays the difference between the working tree and the stage/index area, as well as files not tracked by Git?',0,'`git current`',1,'`git status`',0,'`git local`',0,'`git context`'),
(91,'Q92. Your current repository has three branches: master, beta, and push-notifications. You have just finished the notification feature and commit the changes to the push-notification branch, and you want to include them in the beta branch. How can you accomplish this?',1,'Check out the beta branch and run git merge push-notifications.',0,'Check out the push-notifications branch and run git merge beta.',0,'Check out the master branch and run git merge beta -> push-notifications.',0,'Delete the push-notifications branch; it will be committed to the master branch automatically.'),
(92,'Q93. You would like to restore some previously stashed work to a new branch. How can you do that?',0,'Use `git branch <stash hash>`.',0,'Add the stashed commits to the current commit, then create a new branch.',0,'Use `git checkout -b`.',1,'Run `git stash branch <branch name>`.\n\n[reference here](https://stackoverflow.com/questions/6925099/git-stash-changes-apply-to-new-branch)'),
(93,'Q94. What is the difference between git branch -d and git branch -D?',0,'-D deletes the local branch, while -d deletes the branch regardless of push and merge status.',0,'-d deletes the current commit head, while -D deletes the entire branch.',1,'-d deletes the local branch, while -D deletes the local branch regardless of push and merge status.',0,'-D deletes the current commit head, while -d deletes the entire branch.'),
(94,'Q95. You stashed three sets of changes but cannot remember the contents of the first stash entry. What command would you use to see the details of the changes in the first of the three stash entries?',1,'git stash show -p stash@{2}',0,'git stash list',0,'git stash show -p stash@{1}',0,'git stash show -p\n\n[reference here](https://stackoverflow.com/questions/10725729/see-whats-in-a-stash-without-applying-it)'),
(95,'Q96. Which statement is 1 of the git push command?',1,'By default, a push doesn\'t send tags to the remote repository.',0,'Only annotated tags are automatically pushed to the remote repository with a commit.',0,'Tags are pushed to the remote repository with their respective commits.',0,'Commits can be tagged only when they are created.\n\n[reference here](https://git-scm.com/book/en/v2/Git-Basics-Tagging)'),
(96,'Q97. How would you delete a remote branch in your repository?',0,'Use `git --delete <branch_name>`.',0,'Use `git push <remote_name> --d <branch_name>`.',0,'Use `git push <remote_name> --D`.',1,'Use `git push <remote_name> --delete <branch_name>`.\n\n[reference here](https://stackoverflow.com/questions/2003505/how-do-i-delete-a-git-branch-locally-and-remotely)'),
(97,'Q98. What is the default setting of `git reflog` when no subcommands are specified?',0,'delete',0,'expire',1,'show',0,'update\n\n[reference here](https://git-scm.com/docs/git-reflog)'),
(98,'Q99. How does the `-p` option change the behavior of the `git add` command\n',0,'It causes tracked files in the parent directory to be included in the staged files.',1,'It allows developers to interactively choose which changes to tracked files are staged and outputs the differences for review.',0,'It automatically pushes changes to the corresponding branch on the remote repository.',0,'It allows developers to interactively choose which files are committed and outputs the differences for review.\n\n[reference here](https://git-scm.com/docs/git-add#Documentation/git-add.txt--p)'),
(99,'Q100. After checking out a specific commit, you receive a warning message indicating You are in \'detached HEAD\' state. What is Git warning you of?',1,'You are not working on the most recent commit of a branch.',0,'A teammate has flagged the code with an issue.',0,'The commit does not have a parent.',0,'The branch has not been pushed to the remote repository.\n\n[reference here](https://www.git-tower.com/learn/git/faq/detached-head-when-checkout-commit)'),
(100,'Q101. After accidentally deleting a branch in your local repository, how can you recover it?',0,'It cannot be recovered.',0,'Find the hash of the branch with the `log` command, then execute `git checkout -b <branchname> <hash>`.',1,'Find the hash of the branch with the `reflog` command, then execute `git checkout -b <branchname> <hash>`.',0,'Execute `git checkout -b <branchname>`.\n\n[Reference](https://stackoverflow.com/questions/1992364/git-recover-deleted-remote-branch)'),
(101,'Q102. How would you display a histogram showing inserts, deletion, and modifications per file for a specific commit along with its general commit information?',0,'Use `git stat`.',0,'Use `git debug --prettyprint`.',0,'Query the remote repository with the commit hash.',1,'Use `git show <commit> --stat`.\n\n[Reference](https://git-scm.com/docs/git-show#Documentation/git-show.txt---statltwidthgtltname-widthgtltcountgt)'),
(102,'Q103. What features do repository managers such as GitHub provide beyond Git?',0,'Repository managers are proprietary versions of Git that do not include enhanced features.',0,'Repository managers provide an enhanced command-line tool that is used to manage multiple local repositories.',1,'Repository managers provide an online service for hosting Git repositories that include collaboration features such as pull requests, issue tracking, and peer reviews.',0,'Repository managers distribute repositories across multiple locations on a user\'s workstation, providing redundant storage that allows for quick backup and recovery.\n\n[reference](https://www.theserverside.com/video/Git-vs-GitHub-What-is-the-difference-between-them)'),
(103,'Q104. What command finds the HEAD of the current branch?',0,'`git head --verify`',0,'`git log --head`',0,'`git hash --head`',1,'`git show-ref --head`\n\n[reference](https://git-scm.com/docs/git-show-ref)'),
(104,'Q105. When Git Workflows contain a long-running branch, what purpose does the long-running branch serve?',0,'Long-running branches store unstable code until it os peer reviewed for integration into a feature branch.',0,'Long-running branches correspond to agile sprints and are used to store related to features developed in the sprint.',0,'Long-running branches contain code related to experimental feature development that is merged into short-lived branches such as master.',1,'Long-running branches correspond to different stages of development and are always open for topic/feature branches to be pulled into.'),
(105,'Q106. What command takes changes from the master branch on the remote repository origin and merges then to the local checked-out branch?',0,'`git commit -u origin`',0,'`git checkout origin`',1,'`git pull origin master`',0,'`git push origin master`'),
(106,'Q107. While pushing changes to a remote repository, you receive the following message. How do you resolve this issue?\n\n```bash\nerror: failed to push some refs to \'https://github.com/myrepo/simple.git\'\nhint: Updates were rejected because the remote contains work that you do not hint: not have locally.\n```\n',0,'Use the --atomic option with the push command.',1,'Execute a pull, then resolve any merge conflicts and execute another push.',0,'Execute a fetch, then execute another push.',0,'Use the --force option with the push command.'),
(107,'Q108. What does the -p option add to the output of the `git log` command?',1,'It adds patch output that shows the differences introduced in each commit.',0,'It adds patch output that shows a summary listing modified files.',0,'It adds padding to the output and displays a histogram showing the number of lines changed in each commit.',0,'It adds the full commit message and notes associated with each commit.'),
(108,'Q109. What is the staging area or index?',0,'an area that stores commits prior to them being pushed to the remote repository',0,'an area containing stash entries that can applied to the working files',0,'an area where changes from a branch in the remote repository are stored before they are applied to a local branch',1,'an area that stores information about changes that will be included in the next commit'),
(109,'Q110. What command would you use to stage changes to the index strictly for properties files in the current directory?',1,'`git add *.properties`',0,'`git add %.properties`',0,'`git add .properties`',0,'`git add properties`'),
(110,'Q111. What are untracked files?',0,'files in the local repository that have not been merged into the master branch',0,'staged files that Git does not know about because the have not been committed',1,'files in the working directory that Git does not know about because the have not been staged or committed',0,'files in the remote repository that Git does not know about because they have not been tagged'),
(111,'Q112. What command takes changes from the master branch on the remote repository origin and merges them to the local checked-out branch?',0,'git checkout origin',0,'git commit -u origin',1,'git pull origin master',0,'git push origin master'),
(112,'Q113. What type of Git hook could be used to validate that a commit message contains a ticket number?',0,'pre-commit',1,'commit-msg',0,'applypatch-msg',0,'prepare-commit-msg'),
(113,'Q114. What is the difference between git stash pop and git stash apply?',0,'git stash pop pushes the topmost commit to the current branch, while git stash apply caches the last commit in the current branch.',1,'git stash pop applies the topmost entry in the stash to the working files and removes it from the stash, while git stash apply applies the topmost entry in the stash to the working files but leaves it in the stash.',0,'git stash pop merges the topmost commit to the current branch, while git stash apply merges the last commit in the current branch.',0,'git stash pop applies the topmost entry in the stash to the working files but leaves it in the stash, while git stash apply applies the topmost entry in the stash to the working files and removes it from the stash.'),
(114,'Q115. After making some major changes to your code, you are a little nervous about committing. What command would you use to review the commit prior to making it?',0,'git commit --verify',0,'git notes show',0,'git commit preview',1,'git commit --dry-run'),
(115,'Q116. What statement best describes Git\'s concept of HEAD?',0,'a pointer to the most recently changed file in the stage/index',0,'a pointer to the master branch',1,'a pointer to the most recent commit in the currently checked-out branch',0,'a pointer to where the repository is stored in memory'),
(116,'Q117. After staging changes to several files, you realize the changes to the config.properties file are incorrect, and need to be removed from the stage and working directory. What command can you use to remove the staged changes to the file?',0,'git reset HEAD^ -- config.properties',0,'git rm config.properties',0,'git rf config.properties',1,'git checkout HEAD -- config.properties'),
(117,'Q118. After a recent release with a stack trace, an issue is create that indicates the problem is with a newly added configuration property named MaxConnections. What command can find all commits that add or remove the string MaxConnections?',0,'- git grep -a \'MaxConnections\'',0,'- git log --search-string \'MaxConnections\'',1,'- git log -S \'MaxConnections\'',0,'- git commit --with \'MaxConnections\''),
(118,'Q119. Your company has moved its remote repository to GitHub at this location: https://github.com/yourcompany/core-api.git. What command updates the remote repository, named origin, to point to the new remote repository at this location?',0,'- git remote create-update origin https://github.com/yourcompany/core-api.git',0,'- git remote update origin https://github.com/yourcompany/core-api.git',1,'- git remote set-url origin https://github.com/yourcompany/core-api.git',0,'- git remote add https://github.com/yourcompany/core-api.git'),
(119,'Q120. When is the cherry-pick command used?',1,'- when a commit from one branch needs to be copied into another branch',0,'- when the HEAD needs to be reset to a specific commit',0,'- when a specific commit needs to be pulled down from the remote repository',0,'- when a hook script needs to be invoked'),
(120,'Q121. How would you describe a forked repository?',0,'- a deleted or archived copy of a repository',0,'- a beta release branch of a repository',0,'- a future branch of a repository',1,'- a separate copy of a repository\n\n[reference](https://stackoverflow.com/a/9339460/1573267)'),
(121,'Q122. How can you exclude untracked files within the working directory from a Git repository?',0,'- You cannot exclude the files from the repository.',0,'- Tag the files with excluded.',1,'- Add a pattern matching the files to the .gitignore file.',0,'- Add the files to the omitted branch\n\n[reference](https://git-scm.com/docs/gitignore)'),
(122,'Q123. What command creates a near-exact copy of the entire repository from a server?',0,'`git checkout <url>`',0,'`git pull <url>`',1,'`git clone <url>`',0,'`git replicate <url>`'),
(123,'Q124. What would happen if you ran the `git reset testfile.js` command?',0,'testfile.js would be reverted to a blank file.',0,'testfile.js would be reset to its first saved state.',1,'testfile.js would be reverted to its last saved copy.',0,'testfile.js would be removed from the stage/index area, if present.'),
(124,'Q125. What situation can occur when attempting to combine branches containing changes to the same piece of code?',0,'lost code',0,'automatic override',0,'collisions',1,'merge conflict'),
(125,'Q126. What command creates a near-exact copy of the entire repository from a server?',1,'git clone <url>',0,'git pull <url>',0,'git replicate <url>',0,'git checkout <url>'),
(126,'Q127. When Git workflows contain a topic branch, what purpose does the topic branch serve?',0,'Topic branches store unstable code until it is peer reviewed for integration into another feature branch. <url>',1,'Topic branches correspond to different stages of development and are always open for long-running branches to be pulled into. <url>',0,'Topic branches are used in waterfall development methodologies to track the state of the code during the various stages of waterfall. <url>',0,'Topic branches are short-lived branches used to store work related to a particular feature. <url>'),
(127,'Q128. What practice can help reduce the chances of encountering a merge conflict?',0,'Provide detailed commit messages that describe the changes being introduced by the commit. <url>',0,'make large commits that introduce multiple features. <url>',1,'Keep local repository branches in sync with upstream branches in the remote repository by committing,pushing and pulling frequently. <url>',0,'Avoid frequent interaction with the remote repository to reduce the probability of pulling conflicts. <url>'),
(128,'Q129. What command creates a new branch from the currently checked-out branch?',0,'`git checkout <nameOfBranch>`',1,'`git checkout -b <nameOfBranch>`',0,'`git -b checkout <nameOfBranch>`',0,'`git branch`'),
(129,'Q130. You have changed your mind about adding broccoli to your project. How should you remove it?\n\nUntracked files:\n  (use \'git add <file>...\' to include in what will be committed)\n  brccoli\n',1,'`git remove broccoli`',0,'`git clean -f`',0,'`git clean`',0,'`git remove .`');

/*!40000 ALTER TABLE `quizz` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2022-10-15 13:37:17
